#!/usr/bin/sh
sxhkd &
compton -b --vsync opengl --blur-background --backend glx &
polybar example &
xinput set-prop 14 290 1 &
xinput set-prop 14 298 1 &
blueman-applet &
bspc monitor LVDS-1 -d Terminal Firefox Office Misc

bspc config border_width         1
bspc config window_gap           15
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true 

bspc config pointer_follows_focus	true
bspc config focus_follows_pointer	true
bspc config center_pseudo_tiled		true
bspc config automatic_scheme		spiral

bspc rule -a "URxvt" desktop="^1"
bspc rule -a "Firefox" desktop="^2" 
bspc rule -a "libreoffice-startcenter" desktop="^3"
