#!/usr/bin/sh
sxhkd &
compton -b --vsync opengl --blur-background --backend glx &
$HOME/.config/polybar/launch.sh &
xinput set-prop 15 306 1 &
xinput set-prop 15 314 1 &
blueman-applet &
feh --bg-fill $HOME/Pictures/PeriodicTable.png &
bspc monitor LVDS-1 -d CLI WWW Etc

bspc config border_width         1
bspc config window_gap           15
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true 

bspc config pointer_follows_focus	true
bspc config focus_follows_pointer	true
bspc config center_pseudo_tiled		true
bspc config automatic_scheme		spiral

bspc rule -a "URxvt" desktop="^1"
bspc rule -a "Google-chrome" desktop="^2" 
bspc rule -a "clonehero" desktop="^3"